// **********************************************************************
// Parsed By TarsParser(2.4.5), Generated By tars2node(20200707)
// TarsParser Maintained By <TARS> and tars2node Maintained By <superzheng>
// Generated from "Transaction.tars" by Structure Mode
// **********************************************************************

/* eslint-disable */

"use strict";

var assert    = require("assert");
var TarsStream = require("@tars/stream");

var _hasOwnProperty = Object.prototype.hasOwnProperty;

var bcostars = bcostars || {};
module.exports.bcostars = bcostars;

bcostars.TransactionData = function() {
    this.version = 0;
    this.chainID = "";
    this.groupID = "";
    this.blockLimit = 0;
    this.nonce = "";
    this.to = "";
    this.input = new TarsStream.BinBuffer;
    this.abi = "";
    this._classname = "bcostars.TransactionData";
};
bcostars.TransactionData._classname = "bcostars.TransactionData";
bcostars.TransactionData._write = function (os, tag, value) { os.writeStruct(tag, value); };
bcostars.TransactionData._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
bcostars.TransactionData._readFrom = function (is) {
    var tmp = new bcostars.TransactionData;
    tmp.version = is.readInt32(1, false, 0);
    tmp.chainID = is.readString(2, false, "");
    tmp.groupID = is.readString(3, false, "");
    tmp.blockLimit = is.readInt64(4, false, 0);
    tmp.nonce = is.readString(5, false, "");
    tmp.to = is.readString(6, false, "");
    tmp.input = is.readBytes(7, false, TarsStream.BinBuffer);
    tmp.abi = is.readString(8, false, "");
    return tmp;
};
bcostars.TransactionData.prototype._writeTo = function (os) {
    os.writeInt32(1, this.version);
    os.writeString(2, this.chainID);
    os.writeString(3, this.groupID);
    os.writeInt64(4, this.blockLimit);
    os.writeString(5, this.nonce);
    os.writeString(6, this.to);
    os.writeBytes(7, this.input);
    os.writeString(8, this.abi);
};
bcostars.TransactionData.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
bcostars.TransactionData.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
bcostars.TransactionData.prototype.toObject = function() { 
    return {
        "version" : this.version,
        "chainID" : this.chainID,
        "groupID" : this.groupID,
        "blockLimit" : this.blockLimit,
        "nonce" : this.nonce,
        "to" : this.to,
        "input" : this.input.toObject(),
        "abi" : this.abi
    };
};
bcostars.TransactionData.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "version") && (this.version = json.version);
    _hasOwnProperty.call(json, "chainID") && (this.chainID = json.chainID);
    _hasOwnProperty.call(json, "groupID") && (this.groupID = json.groupID);
    _hasOwnProperty.call(json, "blockLimit") && (this.blockLimit = json.blockLimit);
    _hasOwnProperty.call(json, "nonce") && (this.nonce = json.nonce);
    _hasOwnProperty.call(json, "to") && (this.to = json.to);
    _hasOwnProperty.call(json, "input") && (this.input.readFromObject(json.input));
    _hasOwnProperty.call(json, "abi") && (this.abi = json.abi);
    return this;
};
bcostars.TransactionData.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
bcostars.TransactionData.new = function () {
    return new bcostars.TransactionData();
};
bcostars.TransactionData.create = function (is) {
    return bcostars.TransactionData._readFrom(is);
};

bcostars.Transaction = function() {
    this.data = new bcostars.TransactionData;
    this.dataHash = new TarsStream.BinBuffer;
    this.signature = new TarsStream.BinBuffer;
    this.importTime = 0;
    this.attribute = 0;
    this.sender = new TarsStream.BinBuffer;
    this.extraData = "";
    this._classname = "bcostars.Transaction";
};
bcostars.Transaction._classname = "bcostars.Transaction";
bcostars.Transaction._write = function (os, tag, value) { os.writeStruct(tag, value); };
bcostars.Transaction._read  = function (is, tag, def) { return is.readStruct(tag, true, def); };
bcostars.Transaction._readFrom = function (is) {
    var tmp = new bcostars.Transaction;
    tmp.data = is.readStruct(1, false, bcostars.TransactionData);
    tmp.dataHash = is.readBytes(2, false, TarsStream.BinBuffer);
    tmp.signature = is.readBytes(3, false, TarsStream.BinBuffer);
    tmp.importTime = is.readInt64(4, false, 0);
    tmp.attribute = is.readInt32(5, false, 0);
    tmp.sender = is.readBytes(7, false, TarsStream.BinBuffer);
    tmp.extraData = is.readString(8, false, "");
    return tmp;
};
bcostars.Transaction.prototype._writeTo = function (os) {
    os.writeStruct(1, this.data);
    os.writeBytes(2, this.dataHash);
    os.writeBytes(3, this.signature);
    os.writeInt64(4, this.importTime);
    os.writeInt32(5, this.attribute);
    os.writeBytes(7, this.sender);
    os.writeString(8, this.extraData);
};
bcostars.Transaction.prototype._equal = function () {
    assert.fail("this structure not define key operation");
};
bcostars.Transaction.prototype._genKey = function () {
    if (!this._proto_struct_name_) {
        this._proto_struct_name_ = "STRUCT" + Math.random();
    }
    return this._proto_struct_name_;
};
bcostars.Transaction.prototype.toObject = function() { 
    return {
        "data" : this.data.toObject(),
        "dataHash" : this.dataHash.toObject(),
        "signature" : this.signature.toObject(),
        "importTime" : this.importTime,
        "attribute" : this.attribute,
        "sender" : this.sender.toObject(),
        "extraData" : this.extraData
    };
};
bcostars.Transaction.prototype.readFromObject = function(json) { 
    _hasOwnProperty.call(json, "data") && (this.data.readFromObject(json.data));
    _hasOwnProperty.call(json, "dataHash") && (this.dataHash.readFromObject(json.dataHash));
    _hasOwnProperty.call(json, "signature") && (this.signature.readFromObject(json.signature));
    _hasOwnProperty.call(json, "importTime") && (this.importTime = json.importTime);
    _hasOwnProperty.call(json, "attribute") && (this.attribute = json.attribute);
    _hasOwnProperty.call(json, "sender") && (this.sender.readFromObject(json.sender));
    _hasOwnProperty.call(json, "extraData") && (this.extraData = json.extraData);
    return this;
};
bcostars.Transaction.prototype.toBinBuffer = function () {
    var os = new TarsStream.TarsOutputStream();
    this._writeTo(os);
    return os.getBinBuffer();
};
bcostars.Transaction.new = function () {
    return new bcostars.Transaction();
};
bcostars.Transaction.create = function (is) {
    return bcostars.Transaction._readFrom(is);
};


